//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proServices.SpidInfo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SpidInfo.SpidInfoSoap")]
    public interface SpidInfoSoap {
        
        // CODEGEN: Generating message contract since element name SpidId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpidBasic", ReplyAction="*")]
        proServices.SpidInfo.GetSpidBasicResponse GetSpidBasic(proServices.SpidInfo.GetSpidBasicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpidBasic", ReplyAction="*")]
        System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidBasicResponse> GetSpidBasicAsync(proServices.SpidInfo.GetSpidBasicRequest request);
        
        // CODEGEN: Generating message contract since element name SpidId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpidProducts", ReplyAction="*")]
        proServices.SpidInfo.GetSpidProductsResponse GetSpidProducts(proServices.SpidInfo.GetSpidProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpidProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidProductsResponse> GetSpidProductsAsync(proServices.SpidInfo.GetSpidProductsRequest request);
        
        // CODEGEN: Generating message contract since element name spMapId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpidProductValues", ReplyAction="*")]
        proServices.SpidInfo.GetSpidProductValuesResponse GetSpidProductValues(proServices.SpidInfo.GetSpidProductValuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpidProductValues", ReplyAction="*")]
        System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidProductValuesResponse> GetSpidProductValuesAsync(proServices.SpidInfo.GetSpidProductValuesRequest request);
        
        // CODEGEN: Generating message contract since element name spMapId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpidProductSpecs", ReplyAction="*")]
        proServices.SpidInfo.GetSpidProductSpecsResponse GetSpidProductSpecs(proServices.SpidInfo.GetSpidProductSpecsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpidProductSpecs", ReplyAction="*")]
        System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidProductSpecsResponse> GetSpidProductSpecsAsync(proServices.SpidInfo.GetSpidProductSpecsRequest request);
        
        // CODEGEN: Generating message contract since element name spMapId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpidProductManuals", ReplyAction="*")]
        proServices.SpidInfo.GetSpidProductManualsResponse GetSpidProductManuals(proServices.SpidInfo.GetSpidProductManualsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpidProductManuals", ReplyAction="*")]
        System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidProductManualsResponse> GetSpidProductManualsAsync(proServices.SpidInfo.GetSpidProductManualsRequest request);
        
        // CODEGEN: Generating message contract since element name spMapId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpidProductBenefits", ReplyAction="*")]
        proServices.SpidInfo.GetSpidProductBenefitsResponse GetSpidProductBenefits(proServices.SpidInfo.GetSpidProductBenefitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSpidProductBenefits", ReplyAction="*")]
        System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidProductBenefitsResponse> GetSpidProductBenefitsAsync(proServices.SpidInfo.GetSpidProductBenefitsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpidBasicRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpidBasic", Namespace="http://tempuri.org/", Order=0)]
        public proServices.SpidInfo.GetSpidBasicRequestBody Body;
        
        public GetSpidBasicRequest() {
        }
        
        public GetSpidBasicRequest(proServices.SpidInfo.GetSpidBasicRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpidBasicRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SpidId;
        
        public GetSpidBasicRequestBody() {
        }
        
        public GetSpidBasicRequestBody(string SpidId) {
            this.SpidId = SpidId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpidBasicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpidBasicResponse", Namespace="http://tempuri.org/", Order=0)]
        public proServices.SpidInfo.GetSpidBasicResponseBody Body;
        
        public GetSpidBasicResponse() {
        }
        
        public GetSpidBasicResponse(proServices.SpidInfo.GetSpidBasicResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpidBasicResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSpidBasicResult;
        
        public GetSpidBasicResponseBody() {
        }
        
        public GetSpidBasicResponseBody(string GetSpidBasicResult) {
            this.GetSpidBasicResult = GetSpidBasicResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpidProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpidProducts", Namespace="http://tempuri.org/", Order=0)]
        public proServices.SpidInfo.GetSpidProductsRequestBody Body;
        
        public GetSpidProductsRequest() {
        }
        
        public GetSpidProductsRequest(proServices.SpidInfo.GetSpidProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpidProductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SpidId;
        
        public GetSpidProductsRequestBody() {
        }
        
        public GetSpidProductsRequestBody(string SpidId) {
            this.SpidId = SpidId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpidProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpidProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public proServices.SpidInfo.GetSpidProductsResponseBody Body;
        
        public GetSpidProductsResponse() {
        }
        
        public GetSpidProductsResponse(proServices.SpidInfo.GetSpidProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpidProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSpidProductsResult;
        
        public GetSpidProductsResponseBody() {
        }
        
        public GetSpidProductsResponseBody(string GetSpidProductsResult) {
            this.GetSpidProductsResult = GetSpidProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpidProductValuesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpidProductValues", Namespace="http://tempuri.org/", Order=0)]
        public proServices.SpidInfo.GetSpidProductValuesRequestBody Body;
        
        public GetSpidProductValuesRequest() {
        }
        
        public GetSpidProductValuesRequest(proServices.SpidInfo.GetSpidProductValuesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpidProductValuesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string spMapId;
        
        public GetSpidProductValuesRequestBody() {
        }
        
        public GetSpidProductValuesRequestBody(string spMapId) {
            this.spMapId = spMapId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpidProductValuesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpidProductValuesResponse", Namespace="http://tempuri.org/", Order=0)]
        public proServices.SpidInfo.GetSpidProductValuesResponseBody Body;
        
        public GetSpidProductValuesResponse() {
        }
        
        public GetSpidProductValuesResponse(proServices.SpidInfo.GetSpidProductValuesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpidProductValuesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSpidProductValuesResult;
        
        public GetSpidProductValuesResponseBody() {
        }
        
        public GetSpidProductValuesResponseBody(string GetSpidProductValuesResult) {
            this.GetSpidProductValuesResult = GetSpidProductValuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpidProductSpecsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpidProductSpecs", Namespace="http://tempuri.org/", Order=0)]
        public proServices.SpidInfo.GetSpidProductSpecsRequestBody Body;
        
        public GetSpidProductSpecsRequest() {
        }
        
        public GetSpidProductSpecsRequest(proServices.SpidInfo.GetSpidProductSpecsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpidProductSpecsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string spMapId;
        
        public GetSpidProductSpecsRequestBody() {
        }
        
        public GetSpidProductSpecsRequestBody(string spMapId) {
            this.spMapId = spMapId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpidProductSpecsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpidProductSpecsResponse", Namespace="http://tempuri.org/", Order=0)]
        public proServices.SpidInfo.GetSpidProductSpecsResponseBody Body;
        
        public GetSpidProductSpecsResponse() {
        }
        
        public GetSpidProductSpecsResponse(proServices.SpidInfo.GetSpidProductSpecsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpidProductSpecsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSpidProductSpecsResult;
        
        public GetSpidProductSpecsResponseBody() {
        }
        
        public GetSpidProductSpecsResponseBody(string GetSpidProductSpecsResult) {
            this.GetSpidProductSpecsResult = GetSpidProductSpecsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpidProductManualsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpidProductManuals", Namespace="http://tempuri.org/", Order=0)]
        public proServices.SpidInfo.GetSpidProductManualsRequestBody Body;
        
        public GetSpidProductManualsRequest() {
        }
        
        public GetSpidProductManualsRequest(proServices.SpidInfo.GetSpidProductManualsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpidProductManualsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string spMapId;
        
        public GetSpidProductManualsRequestBody() {
        }
        
        public GetSpidProductManualsRequestBody(string spMapId) {
            this.spMapId = spMapId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpidProductManualsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpidProductManualsResponse", Namespace="http://tempuri.org/", Order=0)]
        public proServices.SpidInfo.GetSpidProductManualsResponseBody Body;
        
        public GetSpidProductManualsResponse() {
        }
        
        public GetSpidProductManualsResponse(proServices.SpidInfo.GetSpidProductManualsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpidProductManualsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSpidProductManualsResult;
        
        public GetSpidProductManualsResponseBody() {
        }
        
        public GetSpidProductManualsResponseBody(string GetSpidProductManualsResult) {
            this.GetSpidProductManualsResult = GetSpidProductManualsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpidProductBenefitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpidProductBenefits", Namespace="http://tempuri.org/", Order=0)]
        public proServices.SpidInfo.GetSpidProductBenefitsRequestBody Body;
        
        public GetSpidProductBenefitsRequest() {
        }
        
        public GetSpidProductBenefitsRequest(proServices.SpidInfo.GetSpidProductBenefitsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpidProductBenefitsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string spMapId;
        
        public GetSpidProductBenefitsRequestBody() {
        }
        
        public GetSpidProductBenefitsRequestBody(string spMapId) {
            this.spMapId = spMapId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpidProductBenefitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpidProductBenefitsResponse", Namespace="http://tempuri.org/", Order=0)]
        public proServices.SpidInfo.GetSpidProductBenefitsResponseBody Body;
        
        public GetSpidProductBenefitsResponse() {
        }
        
        public GetSpidProductBenefitsResponse(proServices.SpidInfo.GetSpidProductBenefitsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSpidProductBenefitsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSpidProductBenefitsResult;
        
        public GetSpidProductBenefitsResponseBody() {
        }
        
        public GetSpidProductBenefitsResponseBody(string GetSpidProductBenefitsResult) {
            this.GetSpidProductBenefitsResult = GetSpidProductBenefitsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SpidInfoSoapChannel : proServices.SpidInfo.SpidInfoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpidInfoSoapClient : System.ServiceModel.ClientBase<proServices.SpidInfo.SpidInfoSoap>, proServices.SpidInfo.SpidInfoSoap {
        
        public SpidInfoSoapClient() {
        }
        
        public SpidInfoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpidInfoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpidInfoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpidInfoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proServices.SpidInfo.GetSpidBasicResponse proServices.SpidInfo.SpidInfoSoap.GetSpidBasic(proServices.SpidInfo.GetSpidBasicRequest request) {
            return base.Channel.GetSpidBasic(request);
        }
        
        public string GetSpidBasic(string SpidId) {
            proServices.SpidInfo.GetSpidBasicRequest inValue = new proServices.SpidInfo.GetSpidBasicRequest();
            inValue.Body = new proServices.SpidInfo.GetSpidBasicRequestBody();
            inValue.Body.SpidId = SpidId;
            proServices.SpidInfo.GetSpidBasicResponse retVal = ((proServices.SpidInfo.SpidInfoSoap)(this)).GetSpidBasic(inValue);
            return retVal.Body.GetSpidBasicResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidBasicResponse> proServices.SpidInfo.SpidInfoSoap.GetSpidBasicAsync(proServices.SpidInfo.GetSpidBasicRequest request) {
            return base.Channel.GetSpidBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidBasicResponse> GetSpidBasicAsync(string SpidId) {
            proServices.SpidInfo.GetSpidBasicRequest inValue = new proServices.SpidInfo.GetSpidBasicRequest();
            inValue.Body = new proServices.SpidInfo.GetSpidBasicRequestBody();
            inValue.Body.SpidId = SpidId;
            return ((proServices.SpidInfo.SpidInfoSoap)(this)).GetSpidBasicAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proServices.SpidInfo.GetSpidProductsResponse proServices.SpidInfo.SpidInfoSoap.GetSpidProducts(proServices.SpidInfo.GetSpidProductsRequest request) {
            return base.Channel.GetSpidProducts(request);
        }
        
        public string GetSpidProducts(string SpidId) {
            proServices.SpidInfo.GetSpidProductsRequest inValue = new proServices.SpidInfo.GetSpidProductsRequest();
            inValue.Body = new proServices.SpidInfo.GetSpidProductsRequestBody();
            inValue.Body.SpidId = SpidId;
            proServices.SpidInfo.GetSpidProductsResponse retVal = ((proServices.SpidInfo.SpidInfoSoap)(this)).GetSpidProducts(inValue);
            return retVal.Body.GetSpidProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidProductsResponse> proServices.SpidInfo.SpidInfoSoap.GetSpidProductsAsync(proServices.SpidInfo.GetSpidProductsRequest request) {
            return base.Channel.GetSpidProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidProductsResponse> GetSpidProductsAsync(string SpidId) {
            proServices.SpidInfo.GetSpidProductsRequest inValue = new proServices.SpidInfo.GetSpidProductsRequest();
            inValue.Body = new proServices.SpidInfo.GetSpidProductsRequestBody();
            inValue.Body.SpidId = SpidId;
            return ((proServices.SpidInfo.SpidInfoSoap)(this)).GetSpidProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proServices.SpidInfo.GetSpidProductValuesResponse proServices.SpidInfo.SpidInfoSoap.GetSpidProductValues(proServices.SpidInfo.GetSpidProductValuesRequest request) {
            return base.Channel.GetSpidProductValues(request);
        }
        
        public string GetSpidProductValues(string spMapId) {
            proServices.SpidInfo.GetSpidProductValuesRequest inValue = new proServices.SpidInfo.GetSpidProductValuesRequest();
            inValue.Body = new proServices.SpidInfo.GetSpidProductValuesRequestBody();
            inValue.Body.spMapId = spMapId;
            proServices.SpidInfo.GetSpidProductValuesResponse retVal = ((proServices.SpidInfo.SpidInfoSoap)(this)).GetSpidProductValues(inValue);
            return retVal.Body.GetSpidProductValuesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidProductValuesResponse> proServices.SpidInfo.SpidInfoSoap.GetSpidProductValuesAsync(proServices.SpidInfo.GetSpidProductValuesRequest request) {
            return base.Channel.GetSpidProductValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidProductValuesResponse> GetSpidProductValuesAsync(string spMapId) {
            proServices.SpidInfo.GetSpidProductValuesRequest inValue = new proServices.SpidInfo.GetSpidProductValuesRequest();
            inValue.Body = new proServices.SpidInfo.GetSpidProductValuesRequestBody();
            inValue.Body.spMapId = spMapId;
            return ((proServices.SpidInfo.SpidInfoSoap)(this)).GetSpidProductValuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proServices.SpidInfo.GetSpidProductSpecsResponse proServices.SpidInfo.SpidInfoSoap.GetSpidProductSpecs(proServices.SpidInfo.GetSpidProductSpecsRequest request) {
            return base.Channel.GetSpidProductSpecs(request);
        }
        
        public string GetSpidProductSpecs(string spMapId) {
            proServices.SpidInfo.GetSpidProductSpecsRequest inValue = new proServices.SpidInfo.GetSpidProductSpecsRequest();
            inValue.Body = new proServices.SpidInfo.GetSpidProductSpecsRequestBody();
            inValue.Body.spMapId = spMapId;
            proServices.SpidInfo.GetSpidProductSpecsResponse retVal = ((proServices.SpidInfo.SpidInfoSoap)(this)).GetSpidProductSpecs(inValue);
            return retVal.Body.GetSpidProductSpecsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidProductSpecsResponse> proServices.SpidInfo.SpidInfoSoap.GetSpidProductSpecsAsync(proServices.SpidInfo.GetSpidProductSpecsRequest request) {
            return base.Channel.GetSpidProductSpecsAsync(request);
        }
        
        public System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidProductSpecsResponse> GetSpidProductSpecsAsync(string spMapId) {
            proServices.SpidInfo.GetSpidProductSpecsRequest inValue = new proServices.SpidInfo.GetSpidProductSpecsRequest();
            inValue.Body = new proServices.SpidInfo.GetSpidProductSpecsRequestBody();
            inValue.Body.spMapId = spMapId;
            return ((proServices.SpidInfo.SpidInfoSoap)(this)).GetSpidProductSpecsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proServices.SpidInfo.GetSpidProductManualsResponse proServices.SpidInfo.SpidInfoSoap.GetSpidProductManuals(proServices.SpidInfo.GetSpidProductManualsRequest request) {
            return base.Channel.GetSpidProductManuals(request);
        }
        
        public string GetSpidProductManuals(string spMapId) {
            proServices.SpidInfo.GetSpidProductManualsRequest inValue = new proServices.SpidInfo.GetSpidProductManualsRequest();
            inValue.Body = new proServices.SpidInfo.GetSpidProductManualsRequestBody();
            inValue.Body.spMapId = spMapId;
            proServices.SpidInfo.GetSpidProductManualsResponse retVal = ((proServices.SpidInfo.SpidInfoSoap)(this)).GetSpidProductManuals(inValue);
            return retVal.Body.GetSpidProductManualsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidProductManualsResponse> proServices.SpidInfo.SpidInfoSoap.GetSpidProductManualsAsync(proServices.SpidInfo.GetSpidProductManualsRequest request) {
            return base.Channel.GetSpidProductManualsAsync(request);
        }
        
        public System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidProductManualsResponse> GetSpidProductManualsAsync(string spMapId) {
            proServices.SpidInfo.GetSpidProductManualsRequest inValue = new proServices.SpidInfo.GetSpidProductManualsRequest();
            inValue.Body = new proServices.SpidInfo.GetSpidProductManualsRequestBody();
            inValue.Body.spMapId = spMapId;
            return ((proServices.SpidInfo.SpidInfoSoap)(this)).GetSpidProductManualsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proServices.SpidInfo.GetSpidProductBenefitsResponse proServices.SpidInfo.SpidInfoSoap.GetSpidProductBenefits(proServices.SpidInfo.GetSpidProductBenefitsRequest request) {
            return base.Channel.GetSpidProductBenefits(request);
        }
        
        public string GetSpidProductBenefits(string spMapId) {
            proServices.SpidInfo.GetSpidProductBenefitsRequest inValue = new proServices.SpidInfo.GetSpidProductBenefitsRequest();
            inValue.Body = new proServices.SpidInfo.GetSpidProductBenefitsRequestBody();
            inValue.Body.spMapId = spMapId;
            proServices.SpidInfo.GetSpidProductBenefitsResponse retVal = ((proServices.SpidInfo.SpidInfoSoap)(this)).GetSpidProductBenefits(inValue);
            return retVal.Body.GetSpidProductBenefitsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidProductBenefitsResponse> proServices.SpidInfo.SpidInfoSoap.GetSpidProductBenefitsAsync(proServices.SpidInfo.GetSpidProductBenefitsRequest request) {
            return base.Channel.GetSpidProductBenefitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<proServices.SpidInfo.GetSpidProductBenefitsResponse> GetSpidProductBenefitsAsync(string spMapId) {
            proServices.SpidInfo.GetSpidProductBenefitsRequest inValue = new proServices.SpidInfo.GetSpidProductBenefitsRequest();
            inValue.Body = new proServices.SpidInfo.GetSpidProductBenefitsRequestBody();
            inValue.Body.spMapId = spMapId;
            return ((proServices.SpidInfo.SpidInfoSoap)(this)).GetSpidProductBenefitsAsync(inValue);
        }
    }
}
